name: biubox
description: "Um jogo nostalgico, num galpão de caixas. Cuidado! As caixas estão caindo!"
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flame: ^1.25.0
  shared_preferences: ^2.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/